services:
  backend:
    build:
      context: ./backend
    environment:
      DB_URL: "sqlite:////data/chips.db"
      JWT_SECRET: "CHANGE_ME_PROD_SECRET"
      JWT_ALGORITHM: "HS256"
      JWT_EXPIRES_MINUTES: "10080"
      CORS_ORIGINS: "http://localhost:3000,http://185.244.50.22:3001"
      SUPERADMIN_USERNAME: "admin"
      SUPERADMIN_PASSWORD: "admin"
    volumes:
      - chips_sqlite:/data
    ports:
      - "8000:8000"       # <-- вот это нужно
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: "http://185.244.50.22:8000"
    environment:
      NODE_ENV: "production"
    ports:
      - "3001:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  chips_sqlite: